name: Deploy - PRODUCTION

on:
  push: # a commit to the specified branches, if any
    branches:
      - master
  workflow_dispatch: # manually executed by a user

jobs:
  deploy-prod:
    uses: ./.github/workflows/_reusable_deploy.yml
    with:
      deploy_env: "production"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.REGION_PRODUCTION }}
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_PRODUCTION }}

  deploy-sandbox:
    uses: ./.github/workflows/_reusable_deploy.yml
    needs: [deploy-prod]
    with:
      deploy_env: "sandbox"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.REGION_SANDBOX }}
      INFRA_CONFIG: ${{ secrets.INFRA_CONFIG_SANDBOX }}
